name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      # RUN TRAINING (THIS IS WHAT YOU WERE MISSING)
      - name: Train model
        run: python scripts/train.py

      # BUILD DOCKER
      - name: Build Docker image
        run: docker build -t churn-ml .

      # UPLOAD ARTIFACTS (VERY IMPORTANT)
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: model-artifacts
          path: |
            model.pkl
            artifacts/
